version: '3'
services:
  nginx:
    image: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
        - .env
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - JhinNet
  mariadb:
    image: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: maria
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - JhinNet
    expose:
      - "3306"
  wordpress:
    image : wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - JhinNet
    expose:
      - "9000"
networks:
  JhinNet:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/hsaktiwy/data/wordpress/"
  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/hsaktiwy/data/mariadb/"