version: '3'
services:
  nginx:
    image: nginx:jhin
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
        - .env
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - JhinNet
  mariadb:
    image: mariadb:jhin
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: maria
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - JhinNet
    expose:
      - "3306"
  wordpress:
    image: wordpress:jhin
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - JhinNet
    expose:
      - "9000"
  redis:
    image:  redis:jhin
    build: 
      context: requirements/redis
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: redis
    restart: on-failure
    networks:
      - JhinNet
    ports:
      - "6379:6379"
    expose:
      - "6379"
networks:
  JhinNet:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/hsaktiwy/data/wordpress/"
  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/Users/hsaktiwy/data/mariadb/"