version: '3'
services:
  nginx:
    image: nginx:jhin
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
        - .env
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - JhinNet
  mariadb:
    image: mariadb:jhin
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - JhinNet
    expose:
      - "3306"
  wordpress:
    image: wordpress:jhin
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: 
      - .env
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - JhinNet
    expose:
      - "9000"
  redis:
    image:  redis:jhin
    build: 
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: redis
    restart: on-failure
    networks:
      - JhinNet
    ports:
      - "6379:6379"
    expose:
      - "6379"
  ftp:
    image: ftp:jhin
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ftp
    restart: on-failure
    networks:
      - JhinNet
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    volumes:
      - wordpress:/ftp/hosting/
    depends_on:
      - wordpress
  adminer:
    image: adminer:jhin
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: adminer
    restart: on-failure
    networks:
      - JhinNet
    ports:
      - "81:81"
    depends_on:
      - wordpress
  website:
    image: website:jhin
    build:
      context: requirements/bonus/website
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: website
    restart: on-failure
    networks:
      - JhinNet
    ports:
      - "80:80"
  cadvisor:
    image: cadviser:jhin
    build:
      context: requirements/bonus/cadviser
      dockerfile: Dockerfile
    container_name: cadvisor
    # check if it can work with docker only
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
    ports:
      - "8080:8080"
    restart: on-failure
networks:
  JhinNet:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/hsaktiwy/data/wordpress/"
  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/hsaktiwy/data/mariadb/"